/* Mexico States */
insert into directory_country_region (country_id, code, default_name) values
  ("MX", "AGU", "Aguascalientes"),
  ("MX", "BCN", "Baja California"),
  ("MX", "BCS", "Baja California Sur"),
  ("MX", "CAM", "Campeche"),
  ("MX", "CHH", "Chihuahua"),
  ("MX", "CHP", "Chiapas"),
  ("MX", "CMX", "Ciudad de México"),
  ("MX", "COA", "Coahuila"),
  ("MX", "COL", "Colima"),
  ("MX", "DUR", "Durango"),
  ("MX", "GUA", "Guanajuato"),
  ("MX", "GRO", "Guerrero"),
  ("MX", "HID", "Hidalgo"),
  ("MX", "JAL", "Jalisco"),
  ("MX", "MEX", "México"),
  ("MX", "MIC", "Michoacán"),
  ("MX", "MOR", "Morelos"),
  ("MX", "NAY", "Nayarit"),
  ("MX", "NLE", "Nuevo León"),
  ("MX", "OAX", "Oaxaca"),
  ("MX", "PUE", "Puebla"),
  ("MX", "QUE", "Querétaro"),
  ("MX", "ROO", "Quintana Roo"),
  ("MX", "SLP", "San Luis Potosí"),
  ("MX", "SIN", "Sinaloa"),
  ("MX", "SON", "Sonora"),
  ("MX", "TAB", "Tabasco"),
  ("MX", "TAM", "Tamaulipas"),
  ("MX", "TLA", "Tlaxcala"),
  ("MX", "VER", "Veracruz"),
  ("MX", "YUC", "Yucatán"),
  ("MX", "ZAC", "Zacatecas");
