<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Category view template
 *
 * @var $block \Magento\Catalog\Block\Category\View
 */
?>
<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
$subcats = $category->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (empty(count($subcats))) {
          if (!$block->isContentMode() || $block->isMixedMode()): ?>
          <div>
            <?= $block->getProductListHtml() ?>
          </div>
        <?php endif;  } ?>
<?php if (!empty(count($subcats))) : ?>
  <style>
  .sidebar.side-bar-main, .block.filter.mana-filter-block {
    display: none;
  }
  </style>
  <div class="subcategories">
    <p class="subcategories-title"><h3> Subcategories </h3></p>
    <ul class="sub-cat" style="list-style-type: none;">
      <?php
      foreach ($subcats as $subcat) {
          $_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
          $_outputhelper = $this->helper('Magento\Catalog\Helper\Output');
          $subcaturl = $subcat->getUrl();
          $_imgHtml = '';
        if ($_imgUrl = $_category->getImageUrl()) {
          $_imgHtml = '<img src="' . $_imgUrl . '" style="width: 35%; height: 35%;"/>';
          $_imgHtml = $_outputhelper->categoryAttribute($_category, $_imgHtml, 'image');
          /* @escapeNotVerified */ } ?>
          <div class="cat">
            <li class="sub-cat">
              <a class="link" href="<?php echo $subcaturl ?>"><?php echo $_imgHtml ?><h4><?php echo $subcat->getName(); ?></h4></a>
            </li></div>
          <?php } ?>
  </ul></div>
<?php endif; ?>
