<?php
/**
 * @copyright   Copyright (c) http://www.manadev.com
 * @license     http://www.manadev.com/license  Proprietary License
 */
/* @author L'Astra Lab
 * @var $block \Manadev\LayeredNavigation\Blocks\Navigation
 *
 * Layers are open by default.
 */
?>

<?php if ($block->isVisible()): ?>
    <div class="block filter mana-filter-block" id="layered-filter-block" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": true, "collateral": { "openedState": "filter-active", "element": "body" } }, "Manadev_LayeredNavigation/js/NavigationView": {}}'>
        <?php $filtered = count(iterator_to_array($block->getAppliedFilters())) ?>
        <div class="block-title filter-title" data-count="<?php echo $filtered; ?>">
            <strong data-role="title"><?php echo __('Filters') ?></strong>
        </div>
        <div class="block-content filter-content">
            <?php if ($block->hasState() && $block->isAppliedFilterVisible()) : ?>
                <div class="filter-current" data-mage-init='{"collapsible":{"openedState": "active", "collapsible": true, "active": true }}'>
                    <strong class="block-subtitle filter-current-subtitle" role="heading" aria-level="2" data-role="title" data-count="<?php echo $filtered; ?>"><?php echo __('Now Filtering by') ?></strong>
                    <ol class="items">
                        <?php foreach ($block->getAppliedFilters() as $engineFilter): ?>
                            <?php foreach ($engineFilter->getAppliedItems() as $item) : ?>
                                <li class="item"><?php echo $block->renderAppliedItem($engineFilter, $item) ?></li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </ol>
                </div>

                <div class="block-actions filter-actions">
                    <a href="<?php echo $block->getClearUrl() ?>"<?php echo $block->getClearLinkAttributes() ?> class="action clear filter-clear"><span><?php echo __('Clear All') ?></span></a>
                </div>
            <?php endif; ?>

            <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?php echo __('Filter options') ?>
                <?php echo $block->getApplyHtml() ?>
            </strong>
            <?php $noFilters = true; ?>
            <div class="filter-options" id="narrow-by-list" data-role="content"
            <?php $range = implode(' ', range(0, 6)); ?> data-mage-init='{"Manadev_Core/js/StatefulAccordionWidget":{"id": "<?php echo $this->getNameInLayout() ?>.filters", "openedState": "active", "collapsible": true, "active": <?php echo $range ?>, "multipleCollapsible": true}}'>
                <?php foreach ($block->getFilters() as $filter): ?>
                    <?php $noFilters = false; ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title"><?php echo __($filter->getName()) ?></div>
                        <div data-role="content" class="filter-options-content"><?php echo $block->renderFilter($filter); ?></div>
                    </div>
                <?php endforeach; ?>
            </div>
            <?php if ($noFilters) : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>

            <?php if($block->getScripts()) : ?>
                <script type="text/x-magento-init">
                    <?php echo $block->renderScripts() ?>
                </script>
            <?php endif; ?>
        </div>
    </div>
<?php endif; ?>
